/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJGallerySizeEnum.h"

NSString *const BJGallerySizeEnumNames[] = {
    [BJGallerySizeEnumSMALL] = @"SMALL",
    [BJGallerySizeEnumMEDIUM] = @"MEDIUM",
    [BJGallerySizeEnumLARGE] = @"LARGE",
};

@implementation BJGallerySizeEnum

- (NSString *)name {
    return BJGallerySizeEnumNames[self.value];
}

+ (NSUInteger)ordinalForName:(NSString *)name {
    if([BJGallerySizeEnumNames[BJGallerySizeEnumSMALL] isEqual:name])
        return BJGallerySizeEnumSMALL;
    if([BJGallerySizeEnumNames[BJGallerySizeEnumMEDIUM] isEqual:name])
        return BJGallerySizeEnumMEDIUM;
    if([BJGallerySizeEnumNames[BJGallerySizeEnumLARGE] isEqual:name])
        return BJGallerySizeEnumLARGE;
    return -1;
}

#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if (![object isKindOfClass:[BJGallerySizeEnum class]])
        return NO;
    BJGallerySizeEnum *that = (BJGallerySizeEnum *)object;
    if (self.value == [that value])
        return YES;
    return NO;
}

@end