/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
#import "BJHasMobileRequestHead.h"
@class BJMobileRequestHead;

@interface BJGetItemsRequestType : BJMutableSpecificRecord<BJHasMobileRequestHead>

/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *take;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *sleep;
@property (nonatomic, readwrite, retain) NSString *validationString;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *generateRandomException;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *returnWrappedErrorResponse;
@property (nonatomic, readwrite, retain) BJMobileRequestHead *head;

- (id)initWithTake:(NSNumber *)take
             sleep:(NSNumber *)sleep
  validationString:(NSString *)validationString
generateRandomException:(NSNumber *)generateRandomException
returnWrappedErrorResponse:(NSNumber *)returnWrappedErrorResponse
              head:(BJMobileRequestHead *)head;

@end