/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJBaseType : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *anyUri1;
/** initValue: int8_t */
@property (nonatomic, readwrite, retain) NSNumber *byte1;
@property (nonatomic, readwrite, retain) NSDecimalNumber *decimal1;
@property (nonatomic, readwrite, retain) NSString *duration1;
/** initValue: float */
@property (nonatomic, readwrite, retain) NSNumber *float1;
/** initValue: short */
@property (nonatomic, readwrite, retain) NSNumber *short1;
/** initValue: uint8_t */
@property (nonatomic, readwrite, retain) NSNumber *unsignedByte1;
/** initValue: unsigned int */
@property (nonatomic, readwrite, retain) NSNumber *unsignedInt1;
/** initValue: unsigned long */
@property (nonatomic, readwrite, retain) NSNumber *unsignedLong1;
/** initValue: unsigned short */
@property (nonatomic, readwrite, retain) NSNumber *unsignedShort1;
@property (nonatomic, readwrite, retain) NSString *guid1;
/** valueType: NSDecimalNumber */
@property (nonatomic, readwrite, retain) NSArray *list1;
/** valueType: NSDecimalNumber */
@property (nonatomic, readwrite, retain) NSArray *list2;

- (id)initWithAnyUri1:(NSString *)anyUri1
                byte1:(NSNumber *)byte1
             decimal1:(NSDecimalNumber *)decimal1
            duration1:(NSString *)duration1
               float1:(NSNumber *)float1
               short1:(NSNumber *)short1
        unsignedByte1:(NSNumber *)unsignedByte1
         unsignedInt1:(NSNumber *)unsignedInt1
        unsignedLong1:(NSNumber *)unsignedLong1
       unsignedShort1:(NSNumber *)unsignedShort1
                guid1:(NSString *)guid1
                list1:(NSArray *)list1
                list2:(NSArray *)list2;

@end