/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJSpecificEnum.h"

enum {
    BJEnum2ValuesCAR,
    BJEnum2ValuesBIKE,
    BJEnum2ValuesPLANE,
};

@interface BJEnum2Values : BJSpecificEnum

@end