/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJEnum2Values.h"

NSString *const BJEnum2ValuesNames[] = {
    [BJEnum2ValuesCAR] = @"CAR",
    [BJEnum2ValuesBIKE] = @"BIKE",
    [BJEnum2ValuesPLANE] = @"PLANE",
};

@implementation BJEnum2Values

- (NSString *)name {
    return BJEnum2ValuesNames[self.value];
}

+ (NSUInteger)ordinalForName:(NSString *)name {
    if([BJEnum2ValuesNames[BJEnum2ValuesCAR] isEqual:name])
        return BJEnum2ValuesCAR;
    if([BJEnum2ValuesNames[BJEnum2ValuesBIKE] isEqual:name])
        return BJEnum2ValuesBIKE;
    if([BJEnum2ValuesNames[BJEnum2ValuesPLANE] isEqual:name])
        return BJEnum2ValuesPLANE;
    return -1;
}

#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if (![object isKindOfClass:[BJEnum2Values class]])
        return NO;
    BJEnum2Values *that = (BJEnum2Values *)object;
    if (self.value == [that value])
        return YES;
    return NO;
}

@end