/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJModelFilling2;
@class BJEnum1Values;

@interface BJModelFilling : BJMutableSpecificRecord

/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *boolfilling;
@property (nonatomic, readwrite, retain) BJEnum1Values *enumfilling;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *intfilling;
@property (nonatomic, readwrite, retain) BJModelFilling2 *modelfilling;
@property (nonatomic, readwrite, retain) NSString *stringfilling1;
@property (nonatomic, readwrite, retain) NSString *stringfilling2;
@property (nonatomic, readwrite, retain) NSString *stringfilling3;
@property (nonatomic, readwrite, retain) NSString *stringfilling4;

- (id)initWithBoolfilling:(NSNumber *)boolfilling
              enumfilling:(BJEnum1Values *)enumfilling
               intfilling:(NSNumber *)intfilling
             modelfilling:(BJModelFilling2 *)modelfilling
           stringfilling1:(NSString *)stringfilling1
           stringfilling2:(NSString *)stringfilling2
           stringfilling3:(NSString *)stringfilling3
           stringfilling4:(NSString *)stringfilling4;

@end