/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJRecord2;

@interface BJRecord2Container : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSArray *record2List;

- (id)initWithRecord2List:(NSArray *)record2List;

@end