/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJTestSerializerSample;
@class BJEnum1Values;
@class BJRecord2Container;
@class BJRecord;

@interface BJTestSerializerSample : BJMutableSpecificRecord

/** initValue: long */
@property (nonatomic, readwrite, retain) NSNumber *bigint1;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *boolean1;
@property (nonatomic, readwrite, retain) NSData *bytes1;
@property (nonatomic, readwrite, retain) BJRecord2Container *container1;
@property (nonatomic, readwrite, retain) NSDate *date1;
/** initValue: double */
@property (nonatomic, readwrite, retain) NSNumber *double1;
@property (nonatomic, readwrite, retain) BJEnum1Values *enum1;
@property (nonatomic, readwrite, retain) BJTestSerializerSample *innerSample;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *int1;
@property (nonatomic, readwrite, retain) NSArray *list1;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *nullableint;
@property (nonatomic, readwrite, retain) BJRecord *record;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *smallint1;
@property (nonatomic, readwrite, retain) NSString *string1;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *tinyint1;
@property (nonatomic, readwrite, retain) NSDictionary *map1;

- (id)initWithBigint1:(NSNumber *)bigint1
             boolean1:(NSNumber *)boolean1
               bytes1:(NSData *)bytes1
           container1:(BJRecord2Container *)container1
                date1:(NSDate *)date1
              double1:(NSNumber *)double1
                enum1:(BJEnum1Values *)enum1
          innerSample:(BJTestSerializerSample *)innerSample
                 int1:(NSNumber *)int1
                list1:(NSArray *)list1
          nullableint:(NSNumber *)nullableint
               record:(BJRecord *)record
            smallint1:(NSNumber *)smallint1
              string1:(NSString *)string1
             tinyint1:(NSNumber *)tinyint1
                 map1:(NSDictionary *)map1;

@end