/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJTestSerializerSample;

@interface BJTestSerializerSampleList : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSArray *samples;

- (id)initWithSamples:(NSArray *)samples;

@end