/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJAmount : BJMutableSpecificRecord

/** initValue: double */
@property (nonatomic, readwrite, retain) NSNumber *value;
@property (nonatomic, readwrite, retain) NSString *currencyId;

- (id)initWithValue:(NSNumber *)value
         currencyId:(NSString *)currencyId;

@end