/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@interface BJCategory : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *categoryId;
@property (nonatomic, readwrite, retain) NSString *categoryName;

- (id)initWithCategoryId:(NSString *)categoryId
            categoryName:(NSString *)categoryName;

@end