/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@interface BJCondition : BJMutableSpecificRecord

/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *conditionId;
@property (nonatomic, readwrite, retain) NSString *conditionDisplayName;

- (id)initWithConditionId:(NSNumber *)conditionId
     conditionDisplayName:(NSString *)conditionDisplayName;

@end