/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJCondition.h"
#import "BJError.h"

@implementation BJCondition

+ (BJSchema *)schema {
    static BJSchema *__schema = nil;
    static dispatch_once_t onceToken;
    dispatch_once (&onceToken, ^{
        __schema = [[BJSchema parse:@"{\"type\":\"record\",\"name\":\"BJCondition\",\"namespace\":\"com.ctrip.soa.framework.soa.testservice.v1\",\"fields\":[{\"name\":\"conditionId\",\"type\":[\"int\",\"null\"]},{\"name\":\"conditionDisplayName\",\"type\":[\"string\",\"null\"]}]}"] retain];
    });
    return __schema;
}

- (id)initWithConditionId:(NSNumber *)conditionId
     conditionDisplayName:(NSString *)conditionDisplayName {
    self = [super init];
    if (self) {
        _conditionId = conditionId;
        _conditionDisplayName = conditionDisplayName;
    }
    return self;
}

- (id)fieldAtIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: return self.conditionId;
        case 1: return self.conditionDisplayName;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in fieldAtIndex:", fieldPos]
                                  userInfo:nil];
    }
    return nil;
}

- (void)setObject:(id)object atIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: self.conditionId = object; break;
        case 1: self.conditionDisplayName = object; break;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in setObject:atIndex:", fieldPos]
                                  userInfo:nil];
    }
}


#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if ([self class] != [object class])
        return NO;
    BJCondition *that = (BJCondition *)object;
    return
    [self.conditionId isEqual:[that conditionId]] &&
    [self.conditionDisplayName isEqual:[that conditionDisplayName]];
}

- (NSUInteger)hash {
    NSUInteger result = 1;
    
    result = 31 * result + (self.conditionId == nil ? 0 : [self.conditionId hash]);
    result = 31 * result + (self.conditionDisplayName == nil ? 0 : [self.conditionDisplayName hash]);
    
    return result;
}

- (void)dealloc {
    [self.conditionId release];
    [self.conditionDisplayName release];
    [super dealloc];
}

@end
