/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJDistance : BJMutableSpecificRecord

/** initValue: double */
@property (nonatomic, readwrite, retain) NSNumber *value;
@property (nonatomic, readwrite, retain) NSString *unit;

- (id)initWithValue:(NSNumber *)value
               unit:(NSString *)unit;

@end