/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJPriceTreatmentEnum;
@class BJMapExposureEnum;
@class BJAmount;

@interface BJDiscountPriceInfo : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) BJAmount *originalRetailPrice;
@property (nonatomic, readwrite, retain) BJMapExposureEnum *minimunAdvertisedPriceExposure;
@property (nonatomic, readwrite, retain) BJPriceTreatmentEnum *pricingTreatment;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *soldOnEbay;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *soldOffEbay;

- (id)initWithOriginalRetailPrice:(BJAmount *)originalRetailPrice
   minimunAdvertisedPriceExposure:(BJMapExposureEnum *)minimunAdvertisedPriceExposure
                 pricingTreatment:(BJPriceTreatmentEnum *)pricingTreatment
                       soldOnEbay:(NSNumber *)soldOnEbay
                      soldOffEbay:(NSNumber *)soldOffEbay;

@end