/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJGalleryURL;

@interface BJGalleryInfoContainer : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSArray *galleryURL;

- (id)initWithGalleryURL:(NSArray *)galleryURL;

@end