/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJSpecificEnum.h"

enum {
    BJGallerySizeEnumSMALL,
    BJGallerySizeEnumMEDIUM,
    BJGallerySizeEnumLARGE,
};

@interface BJGallerySizeEnum : BJSpecificEnum

@end