/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJGallerySizeEnum;

@interface BJGalleryURL : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *value;
@property (nonatomic, readwrite, retain) BJGallerySizeEnum *gallerySize;

- (id)initWithValue:(NSString *)value
        gallerySize:(BJGallerySizeEnum *)gallerySize;

@end