/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJGalleryInfoContainer.h"
#import "BJError.h"
#import "BJGalleryURL.h"

@implementation BJGalleryInfoContainer

+ (BJSchema *)schema {
    static BJSchema *__schema = nil;
    static dispatch_once_t onceToken;
    dispatch_once (&onceToken, ^{
        __schema = [[BJSchema parse:@"{\"type\":\"record\",\"name\":\"BJGalleryInfoContainer\",\"namespace\":\"com.ctrip.soa.framework.soa.testservice.v1\",\"fields\":[{\"name\":\"galleryURL\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"BJGalleryURL\",\"namespace\":\"com.ctrip.soa.framework.soa.testservice.v1\",\"fields\":[{\"name\":\"value\",\"type\":[\"string\",\"null\"]},{\"name\":\"gallerySize\",\"type\":[{\"type\":\"enum\",\"name\":\"BJGallerySizeEnum\",\"namespace\":\"com.ctrip.soa.framework.soa.testservice.v1\",\"symbols\":[\"SMALL\",\"MEDIUM\",\"LARGE\"]},\"null\"]}]}}}]}"] retain];
    });
    return __schema;
}

- (id)initWithGalleryURL:(NSArray *)galleryURL {
    self = [super init];
    if (self) {
        _galleryURL = galleryURL;
    }
    return self;
}

- (id)fieldAtIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: return self.galleryURL;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in fieldAtIndex:", fieldPos]
                                  userInfo:nil];
    }
    return nil;
}

- (void)setObject:(id)object atIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: self.galleryURL = object; break;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in setObject:atIndex:", fieldPos]
                                  userInfo:nil];
    }
}


#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if ([self class] != [object class])
        return NO;
    BJGalleryInfoContainer *that = (BJGalleryInfoContainer *)object;
    return
    [self.galleryURL isEqual:[that galleryURL]];
}

- (NSUInteger)hash {
    NSUInteger result = 1;
    
    result = 31 * result + (self.galleryURL == nil ? 0 : [self.galleryURL hash]);
    
    return result;
}

- (void)dealloc {
    [self.galleryURL release];
    [super dealloc];
}

@end
