/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
#import "BJHasResponseStatus.h"
@class BJResponseStatusType;
@class BJItem;
@interface BJGetItemsResponseType : BJMutableSpecificRecord<BJHasResponseStatus>

@property (nonatomic, readwrite, retain) BJResponseStatusType *responseStatus;
@property (nonatomic, readwrite, retain) NSArray *items;

- (id)initWithResponseStatus:(BJResponseStatusType *)responseStatus
                       items:(NSArray *)items;

@end