/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJItem;

@interface BJItemContainer : BJMutableSpecificRecord

/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *count;
@property (nonatomic, readwrite, retain) NSArray *item;

- (id)initWithCount:(NSNumber *)count
               item:(NSArray *)item;

@end