/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@class BJAmount;

@interface BJListingInfo : BJMutableSpecificRecord

/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *bestOfferEnabled;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *buyItNowAvailable;
@property (nonatomic, readwrite, retain) BJAmount *buyItNowPrice;
@property (nonatomic, readwrite, retain) BJAmount *convertedBuyItNowPrice;
@property (nonatomic, readwrite, retain) NSDate *startTime;
@property (nonatomic, readwrite, retain) NSDate *endTime;
@property (nonatomic, readwrite, retain) NSString *listingType;
/** initValue: bool */
@property (nonatomic, readwrite, retain) NSNumber *gift;

- (id)initWithBestOfferEnabled:(NSNumber *)bestOfferEnabled
             buyItNowAvailable:(NSNumber *)buyItNowAvailable
                 buyItNowPrice:(BJAmount *)buyItNowPrice
        convertedBuyItNowPrice:(BJAmount *)convertedBuyItNowPrice
                     startTime:(NSDate *)startTime
                       endTime:(NSDate *)endTime
                   listingType:(NSString *)listingType
                          gift:(NSNumber *)gift;

@end