/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJMapExposureEnum.h"

NSString *const BJMapExposureEnumNames[] = {
    [BJMapExposureEnumPRE_CHECKOUT] = @"PRE_CHECKOUT",
    [BJMapExposureEnumDURING_CHECKOUT] = @"DURING_CHECKOUT",
};

@implementation BJMapExposureEnum

- (NSString *)name {
    return BJMapExposureEnumNames[self.value];
}

+ (NSUInteger)ordinalForName:(NSString *)name {
    if([BJMapExposureEnumNames[BJMapExposureEnumPRE_CHECKOUT] isEqual:name])
        return BJMapExposureEnumPRE_CHECKOUT;
    if([BJMapExposureEnumNames[BJMapExposureEnumDURING_CHECKOUT] isEqual:name])
        return BJMapExposureEnumDURING_CHECKOUT;
    return -1;
}

#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if (![object isKindOfClass:[BJMapExposureEnum class]])
        return NO;
    BJMapExposureEnum *that = (BJMapExposureEnum *)object;
    if (self.value == [that value])
        return YES;
    return NO;
}

@end