/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJSpecificEnum.h"

enum {
    BJMapExposureEnumPRE_CHECKOUT,
    BJMapExposureEnumDURING_CHECKOUT,
};

@interface BJMapExposureEnum : BJSpecificEnum

@end