/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJProductId : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *value;
@property (nonatomic, readwrite, retain) NSString *type;

- (id)initWithValue:(NSString *)value
               type:(NSString *)type;

@end