/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJPriceTreatmentEnum.h"

NSString *const BJPriceTreatmentEnumNames[] = {
    [BJPriceTreatmentEnumSTP] = @"STP",
    [BJPriceTreatmentEnumMAP] = @"MAP",
};

@implementation BJPriceTreatmentEnum

- (NSString *)name {
    return BJPriceTreatmentEnumNames[self.value];
}

+ (NSUInteger)ordinalForName:(NSString *)name {
    if([BJPriceTreatmentEnumNames[BJPriceTreatmentEnumSTP] isEqual:name])
        return BJPriceTreatmentEnumSTP;
    if([BJPriceTreatmentEnumNames[BJPriceTreatmentEnumMAP] isEqual:name])
        return BJPriceTreatmentEnumMAP;
    return -1;
}

#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if (![object isKindOfClass:[BJPriceTreatmentEnum class]])
        return NO;
    BJPriceTreatmentEnum *that = (BJPriceTreatmentEnum *)object;
    if (self.value == [that value])
        return YES;
    return NO;
}

@end