/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJAmount;

@interface BJSellingStatus : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) BJAmount *currentPrice;
@property (nonatomic, readwrite, retain) BJAmount *convertedCurrentPrice;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *bidCount;
@property (nonatomic, readwrite, retain) NSString *sellingState;
@property (nonatomic, readwrite, retain) NSString *timeLeft;

- (id)initWithCurrentPrice:(BJAmount *)currentPrice
     convertedCurrentPrice:(BJAmount *)convertedCurrentPrice
                  bidCount:(NSNumber *)bidCount
              sellingState:(NSString *)sellingState
                  timeLeft:(NSString *)timeLeft;

@end