/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJStorefront : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *storeName;
@property (nonatomic, readwrite, retain) NSString *storeURL;

- (id)initWithStoreName:(NSString *)storeName
               storeURL:(NSString *)storeURL;

@end