/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@interface BJUnitPriceInfo : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *type;
/** initValue: double */
@property (nonatomic, readwrite, retain) NSNumber *quantity;

- (id)initWithType:(NSString *)type
          quantity:(NSNumber *)quantity;

@end