/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
@class BJSeverityCodeType;
@class BJErrorClassificationCodeType;
@class BJErrorFieldType;

@interface BJErrorDataType : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *message;
@property (nonatomic, readwrite, retain) NSString *errorCode;
@property (nonatomic, readwrite, retain) NSString *stackTrace;
@property (nonatomic, readwrite, retain) BJSeverityCodeType *severityCode;
@property (nonatomic, readwrite, retain) NSArray *errorFields;
@property (nonatomic, readwrite, retain) BJErrorClassificationCodeType *errorClassification;

- (id)initWithMessage:(NSString *)message
            errorCode:(NSString *)errorCode
           stackTrace:(NSString *)stackTrace
         severityCode:(BJSeverityCodeType *)severityCode
          errorFields:(NSArray *)errorFields
  errorClassification:(BJErrorClassificationCodeType *)errorClassification;

@end