/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@interface BJPaginationOutputType : BJMutableSpecificRecord

/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *pageNumber;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *entriesPerPage;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *totalPages;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *totalEntries;

- (id)initWithPageNumber:(NSNumber *)pageNumber
          entriesPerPage:(NSNumber *)entriesPerPage
              totalPages:(NSNumber *)totalPages
            totalEntries:(NSNumber *)totalEntries;

@end