/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@interface BJExtensionFieldType : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *name;
@property (nonatomic, readwrite, retain) NSString *value;

- (id)initWithName:(NSString *)name
             value:(NSString *)value;

@end