/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@class BJExtensionFieldType;

@interface BJMobileRequestHead : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *syscode;
@property (nonatomic, readwrite, retain) NSString *lang;
@property (nonatomic, readwrite, retain) NSString *auth;
@property (nonatomic, readwrite, retain) NSString *cid;
@property (nonatomic, readwrite, retain) NSString *ctok;
@property (nonatomic, readwrite, retain) NSString *cver;
@property (nonatomic, readwrite, retain) NSString *sid;
/** valueType: ExtensionFieldType */
@property (nonatomic, readwrite, retain) NSArray *extension;

- (id)initWithSyscode:(NSString *)syscode
                 lang:(NSString *)lang
                 auth:(NSString *)auth
                  cid:(NSString *)cid
                 ctok:(NSString *)ctok
                 cver:(NSString *)cver
                  sid:(NSString *)sid
            extension:(NSArray *)extension;

@end