/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJExtensionType.h"
#import "BJError.h"

@implementation BJExtensionType

+ (BJSchema *)schema {
    static BJSchema *__schema = nil;
    static dispatch_once_t onceToken;
    dispatch_once (&onceToken, ^{
        __schema = [[BJSchema parse:@"{\"type\":\"record\",\"name\":\"BJExtensionType\",\"namespace\":\"com.ctrip.soa.common.types.v1\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"version\",\"type\":[\"string\",\"null\"]},{\"name\":\"contentType\",\"type\":[\"string\",\"null\"]},{\"name\":\"value\",\"type\":[\"string\",\"null\"]}]}"] retain];
    });
    return __schema;
}

- (id)initWithId:(NSNumber *)id
         version:(NSString *)version
     contentType:(NSString *)contentType
           value:(NSString *)value {
    self = [super init];
    if (self) {
        _id = id;
        _version = version;
        _contentType = contentType;
        _value = value;
    }
    return self;
}

- (id)fieldAtIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: return self.id;
        case 1: return self.version;
        case 2: return self.contentType;
        case 3: return self.value;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in fieldAtIndex:", fieldPos]
                                  userInfo:nil];
    }
    return nil;
}

- (void)setObject:(id)object atIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: self.id = object; break;
        case 1: self.version = object; break;
        case 2: self.contentType = object; break;
        case 3: self.value = object; break;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in setObject:atIndex:", fieldPos]
                                  userInfo:nil];
    }
}


#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if ([self class] != [object class])
        return NO;
    BJExtensionType *that = (BJExtensionType *)object;
    return
    [self.id isEqual:[that id]] &&
    [self.version isEqual:[that version]] &&
    [self.contentType isEqual:[that contentType]] &&
    [self.value isEqual:[that value]];
}

- (NSUInteger)hash {
    NSUInteger result = 1;
    
    result = 31 * result + (self.id == nil ? 0 : [self.id hash]);
    result = 31 * result + (self.version == nil ? 0 : [self.version hash]);
    result = 31 * result + (self.contentType == nil ? 0 : [self.contentType hash]);
    result = 31 * result + (self.value == nil ? 0 : [self.value hash]);
    
    return result;
}

- (void)dealloc {
    [self.id release];
    [self.version release];
    [self.contentType release];
    [self.value release];
    [super dealloc];
}

@end
