/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJSpecificEnum.h"

enum {
    BJAckCodeTypeSUCCESS,
    BJAckCodeTypeFAILURE,
    BJAckCodeTypeWARNING,
    BJAckCodeTypePARTIAL_FAILURE,
};

@interface BJAckCodeType : BJSpecificEnum

@end