/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJAckCodeType.h"

NSString *const BJAckCodeTypeNames[] = {
    [BJAckCodeTypeSUCCESS] = @"SUCCESS",
    [BJAckCodeTypeFAILURE] = @"FAILURE",
    [BJAckCodeTypeWARNING] = @"WARNING",
    [BJAckCodeTypePARTIAL_FAILURE] = @"PARTIAL_FAILURE",
};

@implementation BJAckCodeType

- (NSString *)name {
    return BJAckCodeTypeNames[self.value];
}

+ (NSUInteger)ordinalForName:(NSString *)name {
    if([BJAckCodeTypeNames[BJAckCodeTypeSUCCESS] isEqual:name])
        return BJAckCodeTypeSUCCESS;
    if([BJAckCodeTypeNames[BJAckCodeTypeFAILURE] isEqual:name])
        return BJAckCodeTypeFAILURE;
    if([BJAckCodeTypeNames[BJAckCodeTypeWARNING] isEqual:name])
        return BJAckCodeTypeWARNING;
    if([BJAckCodeTypeNames[BJAckCodeTypePARTIAL_FAILURE] isEqual:name])
        return BJAckCodeTypePARTIAL_FAILURE;
    return -1;
}

#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if (![object isKindOfClass:[BJAckCodeType class]])
        return NO;
    BJAckCodeType *that = (BJAckCodeType *)object;
    if (self.value == [that value])
        return YES;
    return NO;
}

@end