/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJCommonRequestType.h"
#import "BJError.h"

@implementation BJCommonRequestType

- (BJSchema *)schema {
    static BJSchema *__schema = nil;
    static dispatch_once_t onceToken;
    dispatch_once (&onceToken, ^{
        __schema = [[BJSchema parse:@"{\"type\":\"record\",\"name\":\"BJCommonRequestType\",\"namespace\":\"com.ctrip.soa.common.types.v1\",\"fields\":[{\"name\":\"version\",\"type\":[\"string\",\"null\"]},{\"name\":\"outputSelector\",\"type\":{\"type\":\"array\",\"items\":[\"string\",\"null\"]}}]}"] retain];
    });
    return __schema;
}

- (id)initWithVersion:(NSString *)version
       outputSelector:(NSArray *)outputSelector {
    self = [super init];
    if (self) {
        self.version = version;
        self.outputSelector = outputSelector;
    }
    return self;
}

- (id)fieldAtIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: return self.version;
        case 1: return self.outputSelector;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in fieldAtIndex:", fieldPos]
                                  userInfo:nil];
    }
    return nil;
}

- (void)setObject:(id)object atIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: self.version = object; break;
        case 1: self.outputSelector = object; break;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in setObject:atIndex:", fieldPos]
                                  userInfo:nil];
    }
}


#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if ([self class] != [object class])
        return NO;
    BJCommonRequestType *that = (BJCommonRequestType *)object;
    return
    [self.version isEqual:[that version]] &&
    [self.outputSelector isEqual:[that outputSelector]];
}

- (NSUInteger)hash {
    NSUInteger result = 1;
    
    result = 31 * result + (self.version == nil ? 0 : [self.version hash]);
    result = 31 * result + (self.outputSelector == nil ? 0 : [self.outputSelector hash]);
    
    return result;
}

- (void)dealloc {
    [self.version release];
    [self.outputSelector release];
    [super dealloc];
}

@end
