/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJSpecificEnum.h"

enum {
    BJErrorClassificationCodeTypeSERVICE_ERROR,
    BJErrorClassificationCodeTypeVALIDATION_ERROR,
    BJErrorClassificationCodeTypeFRAMEWORK_ERROR,
    BJErrorClassificationCodeTypeSLA_ERROR,
};

@interface BJErrorClassificationCodeType : BJSpecificEnum

@end