/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@interface BJErrorFieldType : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSString *fieldName;
@property (nonatomic, readwrite, retain) NSString *errorCode;
@property (nonatomic, readwrite, retain) NSString *message;

- (id)initWithFieldName:(NSString *)fieldName
              errorCode:(NSString *)errorCode
                message:(NSString *)message;

@end