/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJErrorClassificationCodeType.h"

NSString *const BJErrorClassificationCodeTypeNames[] = {
    [BJErrorClassificationCodeTypeSERVICE_ERROR] = @"SERVICE_ERROR",
    [BJErrorClassificationCodeTypeVALIDATION_ERROR] = @"VALIDATION_ERROR",
    [BJErrorClassificationCodeTypeFRAMEWORK_ERROR] = @"FRAMEWORK_ERROR",
    [BJErrorClassificationCodeTypeSLA_ERROR] = @"SLA_ERROR",
};

@implementation BJErrorClassificationCodeType

- (NSString *)name {
    return BJErrorClassificationCodeTypeNames[self.value];
}

+ (NSUInteger)ordinalForName:(NSString *)name {
    if([BJErrorClassificationCodeTypeNames[BJErrorClassificationCodeTypeSERVICE_ERROR] isEqual:name])
        return BJErrorClassificationCodeTypeSERVICE_ERROR;
    if([BJErrorClassificationCodeTypeNames[BJErrorClassificationCodeTypeVALIDATION_ERROR] isEqual:name])
        return BJErrorClassificationCodeTypeVALIDATION_ERROR;
    if([BJErrorClassificationCodeTypeNames[BJErrorClassificationCodeTypeFRAMEWORK_ERROR] isEqual:name])
        return BJErrorClassificationCodeTypeFRAMEWORK_ERROR;
    if([BJErrorClassificationCodeTypeNames[BJErrorClassificationCodeTypeSLA_ERROR] isEqual:name])
        return BJErrorClassificationCodeTypeSLA_ERROR;
    return -1;
}

#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if (![object isKindOfClass:[BJErrorClassificationCodeType class]])
        return NO;
    BJErrorClassificationCodeType *that = (BJErrorClassificationCodeType *)object;
    if (self.value == [that value])
        return YES;
    return NO;
}

@end