/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJExtensionType : BJMutableSpecificRecord

/** initValue: unsigned long */
@property (nonatomic, readwrite, retain) NSNumber *id;
@property (nonatomic, readwrite, retain) NSString *version;
@property (nonatomic, readwrite, retain) NSString *contentType;
@property (nonatomic, readwrite, retain) NSString *value;

- (id)initWithId:(NSNumber *)id
         version:(NSString *)version
     contentType:(NSString *)contentType
           value:(NSString *)value;

@end