/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"
#import "BJHasResponseStatus.h"
@class BJResponseStatusType;

@interface BJGenericErrorResponseType : BJMutableSpecificRecord<BJHasResponseStatus>

@property (nonatomic, readwrite, retain) BJResponseStatusType *responseStatus;

- (id)initWithResponseStatus:(BJResponseStatusType *)responseStatus;

@end