/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"


@interface BJPaginationInputType : BJMutableSpecificRecord

/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *pageNumber;
/** initValue: int */
@property (nonatomic, readwrite, retain) NSNumber *entriesPerPage;

- (id)initWithPageNumber:(NSNumber *)pageNumber
          entriesPerPage:(NSNumber *)entriesPerPage;

@end