/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import "BJPaginationOutputType.h"
#import "BJError.h"

@implementation BJPaginationOutputType

- (BJSchema *)schema {
    static BJSchema *__schema = nil;
    static dispatch_once_t onceToken;
    dispatch_once (&onceToken, ^{
        __schema = [[BJSchema parse:@"{\"type\":\"record\",\"name\":\"BJPaginationOutputType\",\"namespace\":\"com.ctrip.soa.common.types.v1\",\"fields\":[{\"name\":\"pageNumber\",\"type\":[\"int\",\"null\"]},{\"name\":\"entriesPerPage\",\"type\":[\"int\",\"null\"]},{\"name\":\"totalPages\",\"type\":[\"int\",\"null\"]},{\"name\":\"totalEntries\",\"type\":[\"int\",\"null\"]}]}"] retain];
    });
    return __schema;
}

- (id)initWithPageNumber:(NSNumber *)pageNumber
          entriesPerPage:(NSNumber *)entriesPerPage
              totalPages:(NSNumber *)totalPages
            totalEntries:(NSNumber *)totalEntries {
    self = [super init];
    if (self) {
        self.pageNumber = pageNumber;
        self.entriesPerPage = entriesPerPage;
        self.totalPages = totalPages;
        self.totalEntries = totalEntries;
    }
    return self;
}

- (id)fieldAtIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: return self.pageNumber;
        case 1: return self.entriesPerPage;
        case 2: return self.totalPages;
        case 3: return self.totalEntries;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in fieldAtIndex:", fieldPos]
                                  userInfo:nil];
    }
    return nil;
}

- (void)setObject:(id)object atIndex:(int)fieldPos {
    switch (fieldPos) {
        case 0: self.pageNumber = object; break;
        case 1: self.entriesPerPage = object; break;
        case 2: self.totalPages = object; break;
        case 3: self.totalEntries = object; break;
        default:
            [NSException exceptionWithName:BJRuntimeException
                                    reason:[NSString stringWithFormat:@"Bad index %d in setObject:atIndex:", fieldPos]
                                  userInfo:nil];
    }
}


#pragma override NSObject methods

- (BOOL)isEqual:(id)object {
    if (object == nil)
        return NO;
    if ([self class] != [object class])
        return NO;
    BJPaginationOutputType *that = (BJPaginationOutputType *)object;
    return
    [self.pageNumber isEqual:[that pageNumber]] &&
    [self.entriesPerPage isEqual:[that entriesPerPage]] &&
    [self.totalPages isEqual:[that totalPages]] &&
    [self.totalEntries isEqual:[that totalEntries]];
}

- (NSUInteger)hash {
    NSUInteger result = 1;
    
    result = 31 * result + (self.pageNumber == nil ? 0 : [self.pageNumber hash]);
    result = 31 * result + (self.entriesPerPage == nil ? 0 : [self.entriesPerPage hash]);
    result = 31 * result + (self.totalPages == nil ? 0 : [self.totalPages hash]);
    result = 31 * result + (self.totalEntries == nil ? 0 : [self.totalEntries hash]);
    
    return result;
}

- (void)dealloc {
    [self.pageNumber release];
    [self.entriesPerPage release];
    [self.totalPages release];
    [self.totalEntries release];
    [super dealloc];
}

@end
