/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJMutableSpecificRecord.h"

@class BJErrorDataType;
@class BJExtensionType;
@class BJAckCodeType;

@interface BJResponseStatusType : BJMutableSpecificRecord

@property (nonatomic, readwrite, retain) NSDate *timestamp;
@property (nonatomic, readwrite, retain) BJAckCodeType *ack;
/** valueType: ErrorDataType */
@property (nonatomic, readwrite, retain) NSArray *errors;
@property (nonatomic, readwrite, retain) NSString *build;
@property (nonatomic, readwrite, retain) NSString *version;
/** valueType: ExtensionType */
@property (nonatomic, readwrite, retain) NSArray *extension;

- (id)initWithTimestamp:(NSDate *)timestamp
                    ack:(BJAckCodeType *)ack
                 errors:(NSArray *)errors
                  build:(NSString *)build
                version:(NSString *)version
              extension:(NSArray *)extension;

@end