/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
#import <Foundation/Foundation.h>
#import "BJSpecificEnum.h"

enum {
    BJSeverityCodeTypeERROR,
    BJSeverityCodeTypeWARNING,
};

@interface BJSeverityCodeType : BJSpecificEnum

@end